# http://docs.travis-ci.com/user/customizing-the-build/
language: python
python:
matrix:
  include:
    - python: "2.6"
      env: TEST_SUITE=suite_2_6
    - python: "2.7"
      env: TEST_SUITE=suite_2_7
    - python: "3.2"
      env: TEST_SUITE=suite_3_2
    - python: "3.3"
      env: TEST_SUITE=suite_3_3
    - python: "3.4"
      env: TEST_SUITE=suite_3_4
    - python: "pypy"
      env: TEST_SUITE=suite_pypy
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "3.3"
  fast_finish: true
before_install:
	- sudo apt-get update -qq
	- sudo apt-get install -qq cowsay
install:
  - pip install -r requirements-dev.txt
#before_script:
script:
  - nosetests
after_success:
  - cowsay "Build OK!"
after_failure:
  - cowsay "Build failed!"
#after_script:
#before_deploy:
#deploy:
#  provider: heroku
#  api_key: "YOUR API KEY"
#after_deploy:

