# http://docs.travis-ci.com/user/customizing-the-build/
language: python
matrix:
  include:
  - python: '2.6'
    env: TEST_SUITE=suite_2_6
  - python: '2.7'
    env: TEST_SUITE=suite_2_7
  - python: '3.2'
    env: TEST_SUITE=suite_3_2
  - python: '3.3'
    env: TEST_SUITE=suite_3_3
  - python: '3.4'
    env: TEST_SUITE=suite_3_4
  - python: pypy
    env: TEST_SUITE=suite_pypy
  allow_failures:
  - python: '2.6'
  - python: '3.2'
  - python: '3.3'
  fast_finish: true
install:
- pip install -r requirements-dev.txt
before_deploy:
  export PATH="$PATH:$HOME/.local/bin"
deploy:
  provider: heroku
  api_key:
    secure: "TiKEC1UKeG2/mUfJvBSsDVm8ju2IxvOn9td3pO83HMNzJtp+DtaCMpIO4YL03MOJ9WaMbtpkpEeovlSEAeIJ7v0xkbsLQtxmZDNPWJ/A0YX85+sE8RaQnWnVEDhLy9C+Pk4HyAkbl+lqZz7G79kbIq9TZnH+baop5fiq8PpCKiI="
  app: cuturl
  run:
  - restart
script:
- nosetests
notifications:
  email:
    recipients:
      - bartoszgo@gmail.com
    on_success: always
    on_failure: always
