language: python
sudo: false
matrix:
  include:
  - python: '3.7'
    env: TEST_SUITE=suite_3_7
  fast_finish: true
install:
- python --version
- pip --version
- pip install -r requirements-global.txt
- pip install -r requirements-dev.txt
script:
- nosetests --with-coverage tests
- behave
after_success:
before_deploy:
- export PATH="$PATH:$HOME/.local/bin"
deploy:
- provider: heroku
  skip_cleanup: true
  api_key:
    secure: X90284NMpUqYqEqwdBDTeV3FbHnxwWVK+Bej4gOwtdvTxWqH0j3KZ2OfrQk5RVz/EVQiG6jsO2bkUyOIJA98q8PDMc24ijaAyU+0kom4iNebrD9tiHW0OuMbygte1S4I4t+PeY1yKk+vNklFA7mu7cIsEzNruRE2h/60Wb0EFS4=
  app: fathomless-everglades-8154

